name: Lint, Build, and Publish Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Authenticate to GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Bump Package Version
        run: pnpm version patch --no-git-tag-version
        
        if: github.ref == 'refs/heads/main'
      - name: Commit Version Change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: version bump"
          git push
        if: github.ref == 'refs/heads/main'

      - name: Build package
        run: pnpm build

      - name: Publish package
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm publish --access restricted --registry=https://npm.pkg.github.com || echo "Skipping publish due to version conflict."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
